// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa3AhTnULjeCLfN0Dv4WoG7-vLCUbbFtY',
    appId: '1:43716552411:web:98683b788fb7cb75d8cefe',
    messagingSenderId: '43716552411',
    projectId: 'test-auth-integration-failing',
    authDomain: 'test-auth-integration-failing.firebaseapp.com',
    storageBucket: 'test-auth-integration-failing.appspot.com',
    measurementId: 'G-ZCJXLKY1V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFtCLparjFqfe3UUB4EnMoZWEFMq8hMfI',
    appId: '1:43716552411:android:35e03b492a230eb5d8cefe',
    messagingSenderId: '43716552411',
    projectId: 'test-auth-integration-failing',
    storageBucket: 'test-auth-integration-failing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf-9IWomSsy5rMRkz4_pTqdxZv7ZBGYUY',
    appId: '1:43716552411:ios:5696a411e88aa964d8cefe',
    messagingSenderId: '43716552411',
    projectId: 'test-auth-integration-failing',
    storageBucket: 'test-auth-integration-failing.appspot.com',
    iosClientId: '43716552411-ppij8uqruvtikb16r206malb2j26t5g8.apps.googleusercontent.com',
    iosBundleId: 'com.ex',
  );
}
